"""add sms_logs and blocklist tables

Revision ID: 4b28d3e71e4c
Revises: 7bb612a9d908
Create Date: 2026-03-16 19:32:50.075448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b28d3e71e4c'
down_revision = '7bb612a9d908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('recipient_role', sa.String(length=20), nullable=True))
        batch_op.drop_column('patient_name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar_url',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar_url',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('sms_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_name', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('recipient_role')
        batch_op.drop_column('recipient_name')

    # ### end Alembic commands ###
